import os
import requests
import json
from datetime import datetime

class EmailSender:
    def __init__(self):
        self.api_key = os.environ.get("RESEND_API_KEY")
        self.sender_email = os.environ.get("SENDER_EMAIL", "onboarding@resend.dev") # Default Resend test email
        self.admin_email = os.environ.get("ADMIN_EMAIL", "adham@agritech.com") # Target

    def send(self, recipient, subject, body):
        """
        Sends an email using the Resend API.
        """
        if not self.api_key:
            print(f"⚠️ [EMAIL] RESEND_API_KEY not found. Simulating email to {recipient}: {subject}")
            return False

        url = "https://api.resend.com/emails"
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }
        
        payload = {
            "from": f"OSIRIS Intelligence <{self.sender_email}>",
            "to": [recipient],
            "subject": f"🦅 [OSIRIS] {subject}",
            "html": f"""
            <div style="font-family: monospace; background-color: #0f172a; color: #e2e8f0; padding: 20px; border-radius: 8px;">
                <h2 style="color: #4ade80;">OSIRIS INTELLIGENCE REPORT</h2>
                <p><strong>Time:</strong> {datetime.now().isoformat()}</p>
                <hr style="border-color: #334155;">
                <div style="white-space: pre-wrap;">{body}</div>
                <hr style="border-color: #334155;">
                <p style="font-size: 10px; color: #64748b;">Generated by Adham AgriTech Sovereign Core.</p>
            </div>
            """
        }

        try:
            response = requests.post(url, headers=headers, json=payload)
            if response.status_code in [200, 201]:
                print(f"✅ [EMAIL] Sent successfully to {recipient}")
                return True
            else:
                print(f"❌ [EMAIL] Failed to send: {response.text}")
                return False
        except Exception as e:
            print(f"❌ [EMAIL] Exception: {str(e)}")
            return False
